#define IF 1
#define ELSE 2
#define RETURN 3
#define INT 4
#define VOID 5
#define WHILE 6
#define ID 7
#define NUM 8
#define Op_lessequal 9
#define Op_greaterequal 10
#define Op_equal 11
#define Op_notequal 12
#define LeftPrnts 13
#define RightPrnts 14
#define LeftBrack 15
#define RightBrack 16
#define LeftBrace 17
#define RightBrace 18
#define Op_add 19
#define Op_subtract 20
#define Op_multiply 21
#define Op_divide 22
#define Op_mod 23
#define Op_less 24
#define Op_greater 25
#define Op_assign 26
#define Semicolon 27
#define Comma 28
#define Eps 29
